# Checkov Configuration for Development Environment
# This configuration skips checks that are not appropriate for development environments

framework:
  - terraform

skip-check:
  # Service Plan and Application Service checks that are not needed for dev
  - CKV_AZURE_225 # App Service Plan zone redundancy not required for dev
  - CKV_AZURE_212 # Minimum instances for failover not required for dev
  - CKV_AZURE_211 # Production-suitable SKU not required for dev

  # Authentication and authorization not set up in dev
  - CKV_AZURE_16 # Azure AD registration not required for dev
  - CKV_AZURE_13 # App Service authentication not required for dev

  # Development-specific settings that would interfere with debugging
  - CKV_AZURE_222 # Public network access needed for dev
  - CKV_AZURE_17 # Client certificates not needed for dev

  # Logging and monitoring not fully configured in dev
  - CKV_AZURE_66 # Failed request tracing not needed for dev
  - CKV_AZURE_63 # HTTP logging not needed for dev
  - CKV_AZURE_65 # Detailed error messages not needed for dev
  - CKV_AZURE_213 # Health check not configured for dev

  # Storage and identity settings appropriate for dev environment
  - CKV_AZURE_88 # Azure Files not used in dev
  - CKV_AZURE_71 # Managed identity not configured for dev
  - CKV2_AZURE_33 # Private endpoints not used in dev
  - CKV2_AZURE_1 # Customer managed keys not used in dev
  - CKV2_AZURE_40 # "Ensure storage account is not configured with Shared Key authorization"

  # Storage account settings for flow logs (dev-appropriate)
  - CKV_AZURE_206 # Storage replication not critical for dev flow logs
  - CKV_AZURE_33 # Queue service logging not needed for dev
  - CKV_AZURE_44 # Latest TLS version not enforced for dev
  - CKV_AZURE_59 # Public access restriction not enforced for dev

  # Service Bus security settings not required for dev environment
  - CKV_AZURE_199 # Double encryption not required for dev
  - CKV_AZURE_201 # Customer-managed key not required for dev
  - CKV_AZURE_202 # Managed identity not required for dev
  - CKV_AZURE_203 # Local authentication needed for dev
  - CKV_AZURE_204 # Public network access needed for dev
  - CKV_AZURE_205 # Latest TLS version not enforced for dev

  # PostgreSQL Database
  - CKV2_AZURE_57  #"Ensure PostgreSQL Flexible Server is configured with private endpoint"
  - CKV_AZURE_136  #"Ensure that PostgreSQL Flexible server enables geo-redundant backups"

  # Ensure Terraform module sources use a commit hash"
  - CKV_TF_1 #"Ensure Terraform module sources use a commit hash"

  # GitHub Self-hosted Runner - Expected failures for functionality
  - CKV_AZURE_178 # "Ensure linux VM enables SSH with keys for secure communication" - Runner needs SSH access
  - CKV_AZURE_50  # "Ensure Virtual Machine Extensions are not Installed" - Runner needs extensions for GitHub Actions
  - CKV_AZURE_119 # "Ensure that Network Interfaces don't use public IPs" - Runner needs public IP to communicate with GitHub

# Skip parsing issues with complex policy definitions
skip-path:
  - /infrastructure/terraform/modules/policies/main.tf# Output format
output: cli

# Quiet mode - only show failures
quiet: false

# Show only failed checks
compact: true
