services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/azure-policy:cached
    command: sleep infinity
    depends_on:
      - azurite
    networks:
      - functions-net
    environment:
      - AZURITE_ACCOUNT_NAME=devstoreaccount1
      - AZURITE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    command: "azurite --silent --location /data --debug /data/debug.log --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    networks:
      - functions-net

networks:
  functions-net:
    driver: bridge

volumes:
  azurite-data:
