name: Pre-commit

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          update-environment: true

      - name: Create python symlink
        run: |
          # Ensure python command is available (some hooks expect 'python' not 'python3')
          sudo ln -sf "$(which python3)" /usr/local/bin/python || true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq shellcheck

      - name: Install PowerShell modules
        run: |
          # Install PowerShell Core
          wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
          # Install PSScriptAnalyzer module for PowerShell analysis
          pwsh -Command "Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted"
          pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -Verbose"
          # Verify PSScriptAnalyzer installation
          pwsh -Command "Get-Module -ListAvailable PSScriptAnalyzer"

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
          # Configure HCP Terraform (Terraform Cloud) CLI credentials for private registry/module access
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Verify Terraform Cloud token and export env
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
        run: |
          set -euo pipefail
          echo "Verifying Terraform Cloud token and organization..."
          if [ -z "${TF_API_TOKEN:-}" ]; then
            echo "Warning: TF_API_TOKEN is not set; private module initialization may fail."
          fi
          if [ -z "${TF_CLOUD_ORGANIZATION:-}" ]; then
            echo "Warning: TF_CLOUD_ORGANIZATION is not set; skipping API verification."
          else
            if [ -n "${TF_API_TOKEN:-}" ]; then
              # Fail fast if token/org are invalid (401/404)
              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
                -H "Authorization: Bearer ${TF_API_TOKEN}" \
                -H "Content-Type: application/vnd.api+json" \
                "https://app.terraform.io/api/v2/organizations/${TF_CLOUD_ORGANIZATION}")
              if [ "$http_code" -ge 400 ]; then
                echo "Error: Terraform Cloud token verification failed with status $http_code" >&2
                exit 1
              fi
              echo "Terraform Cloud token verified (HTTP $http_code)."
            fi
          fi
          # Export TF_TOKEN_app_terraform_io so any child tools/hooks also pick it up
          if [ -n "${TF_API_TOKEN:-}" ]; then
            echo "TF_TOKEN_app_terraform_io=${TF_API_TOKEN}" >> "$GITHUB_ENV"
            echo "Exported TF_TOKEN_app_terraform_io for Terraform CLI consumers."
          fi

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Install terraform-docs
        run: |
          # Install terraform-docs for automatic documentation generation
          curl -sSLo terraform-docs.tar.gz "https://github.com/terraform-docs/terraform-docs/releases/download/v0.20.0/terraform-docs-v0.20.0-linux-amd64.tar.gz"
          tar -xzf terraform-docs.tar.gz
          sudo mv terraform-docs /usr/local/bin/
          rm terraform-docs.tar.gz
          # Verify installation
          terraform-docs --version
          echo "terraform-docs installed successfully"

      - name: Initialize Terraform modules for documentation
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
        run: |
          echo "Initializing Terraform modules for documentation generation..."
          # Find all directories containing Terraform files
          for dir in infrastructure/*/; do
            if [[ -d "$dir" && (-f "$dir/main.tf" || -f "$dir/variables.tf" || -f "$dir/outputs.tf") ]]; then
              echo "Initializing $dir"
              cd "$dir"
              # Initialize with error handling for modules that require authentication
              terraform init -backend=false -upgrade=false || {
                echo "Warning: Failed to initialize $dir (this may be expected for modules requiring authentication)"
              }
              # Remove .terraform directory but keep .terraform.lock.hcl
              rm -rf .terraform/ 2>/dev/null || true
              cd - > /dev/null
            fi
          done

      - name: Debug terraform-docs before pre-commit
        run: |
          echo "Current terraform-docs status before pre-commit:"
          find infrastructure/ -name "README.md" -exec echo "=== {} ===" \; -exec head -5 {} \;
          echo "Terraform provider versions after init:"
          find infrastructure/ -name ".terraform.lock.hcl" -exec echo "=== {} ===" \; -exec head -10 {} \; || echo "No lock files found"

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Install pre-commit
        run: |
          pip install --upgrade pip
          pip install pre-commit
          # Verify pre-commit installation
          pre-commit --version

      - name: Validate configuration files
        run: |
          echo "Validating configuration files..."
          echo "Current working directory: $(pwd)"
          echo "Checkov config exists: $(test -f .checkov.yaml && echo 'YES' || echo 'NO')"
          echo "Pre-commit config exists: $(test -f .pre-commit-config.yaml && echo 'YES' || echo 'NO')"
          echo "Validating pre-commit config syntax..."
          pre-commit validate-config
          echo "Configuration validation completed."

      - name: Install pre-commit hooks
        run: |
          pre-commit install --install-hooks

      - name: Verify tool installations
        run: |
          echo "Verifying tool installations..."
          echo "Python version: $(python --version 2>/dev/null || echo 'python not available')"
          echo "Python3 version: $(python3 --version 2>/dev/null || echo 'python3 not available')"
          echo "Python path: $(which python 2>/dev/null || echo 'python not found')"
          echo "Python3 path: $(which python3 2>/dev/null || echo 'python3 not found')"
          echo "PowerShell version: $(pwsh --version 2>/dev/null || echo 'PowerShell not available')"
          echo "Azure CLI version: $(az --version 2>/dev/null | head -1 || echo 'Azure CLI not available')"
          echo "Terraform version: $(terraform --version 2>/dev/null | head -1 || echo 'Terraform not available')"
          echo "TFLint version: $(tflint --version 2>/dev/null || echo 'TFLint not available')"
          echo "Checkov version: $(checkov --version 2>/dev/null || echo 'Checkov not available')"
          echo "jq version: $(jq --version 2>/dev/null || echo 'jq not available')"
          echo "shellcheck version: $(shellcheck --version 2>/dev/null | head -1 || echo 'shellcheck not available')"
          echo "PSScriptAnalyzer check:"
          pwsh -Command "Get-Module -ListAvailable PSScriptAnalyzer | Select-Object Name,Version | Format-Table -AutoSize" 2>/dev/null || echo 'PSScriptAnalyzer not available'
          echo "Pre-commit version: $(pre-commit --version)"
          echo "Tool verification completed."

      - name: Run pre-commit on all files
        id: precommit
        continue-on-error: true
        env:
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}
          EVENT_NAME: ${{ github.event_name }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: |
          echo "Running pre-commit checks on all files..."
          echo "Working directory: $(pwd)"
          echo "Current branch: $(git branch --show-current)"
          echo "Git status before pre-commit:"
          git status --porcelain
          echo "Pre-commit config validation:"
          pre-commit validate-config
          echo "Starting pre-commit run..."

          # Run pre-commit and capture exit code
          if pre-commit run --all-files --show-diff-on-failure --verbose; then
            echo "✅ All pre-commit checks passed!"
            exit 0
          else
            precommit_exit_code=$?
            echo "Pre-commit failed with exit code: $precommit_exit_code"

            # Check if files were modified by terraform-docs
            if ! git diff --quiet; then
              modified_files=$(git diff --name-only)
              echo "Files were modified during pre-commit:"
              echo "$modified_files"

              # Check if only README.md files were modified (terraform-docs changes)
              if echo "$modified_files" | grep -E '(^README\.md$|^infrastructure/.*/README\.md$)' > /dev/null && ! echo "$modified_files" | grep -v -E '(^README\.md$|^infrastructure/.*/README\.md$)' > /dev/null; then
                echo "Only README.md files were modified by terraform-docs"
                echo "This indicates terraform-docs updated documentation due to environment differences"
                echo "Auto-committing terraform-docs changes..."

                # Configure git for the action
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"

                # Add and commit the changes
                git add README.md infrastructure/*/README.md 2>/dev/null || true
                if git commit -m "docs: auto-update terraform documentation via CI [skip ci]"; then
                  echo "✅ terraform-docs changes have been committed"

                  # Push the changes back to the repository
                  if [ "$EVENT_NAME" = "pull_request" ]; then
                    # For pull requests, push to the PR branch
                    git push origin HEAD:"$HEAD_REF"
                    echo "✅ Changes pushed to PR branch: $HEAD_REF"
                  else
                    # For push events, push to the current branch
                    git push origin HEAD:"$REF_NAME"
                    echo "✅ Changes pushed to branch: $REF_NAME"
                  fi

                  echo "Re-running pre-commit to verify..."
                  # Re-run pre-commit to make sure everything passes now
                  if pre-commit run --all-files --show-diff-on-failure --verbose; then
                    echo "✅ All checks passed after auto-commit!"
                    exit 0
                  else
                    echo "❌ Pre-commit still failing after auto-commit"
                    exit 1
                  fi
                else
                  echo "No changes to commit"
                fi
              else
                echo "Non-terraform-docs files were modified or other issues detected"
                echo "Modified files:"
                echo "$modified_files"
                git diff --name-status
                exit $precommit_exit_code
              fi
            else
              echo "No files were modified, but pre-commit failed"
              exit $precommit_exit_code
            fi
          fi

      - name: Debug terraform-docs after pre-commit failure
        if: failure()
        run: |
          echo "Files modified during pre-commit run:"
          git status --porcelain
          echo "Detailed diff of any changes:"
          git diff
          echo "Terraform-docs version and config check:"
          terraform-docs --version
          find infrastructure/ -name ".terraform-docs.yml" -exec echo "=== {} ===" \; -exec cat {} \;

      - name: Generate summary report
        if: always()
        run: |
          {
            echo "## Pre-commit Check Results"
            echo ""
          } >> "$GITHUB_STEP_SUMMARY"

          if [ "${{ steps.precommit.outcome }}" == "success" ]; then
            echo "✅ **All pre-commit checks passed successfully!**" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "❌ **Some pre-commit checks failed. Please review the output above.**" >> "$GITHUB_STEP_SUMMARY"
          fi

          {
            echo ""
            echo "### Checks performed:"
            echo "- File formatting (trailing whitespace, end of files)"
            echo "- YAML, JSON, TOML, XML validation"
            echo "- Python code formatting (Black, isort)"
            echo "- Python linting (flake8)"
            echo "- Python type checking (mypy, pyright)"
            echo "- Python code cleanup (autoflake - removes unused imports/variables)"
            echo "- Jupyter notebook cleaning and linting"
            echo "- PowerShell script analysis"
            echo "- Shell script linting (shellcheck)"
            echo "- Azure Policy JSON validation"
            echo "- Bicep template validation"
            echo "- Terraform formatting and validation"
            echo "- GitHub Actions workflow linting"
            echo "- Security scanning (bandit)"
            echo "- Secrets detection (detect-secrets)"
            echo "- Documentation structure enforcement"
            echo ""
            echo "**Timestamp:** $(date)"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Check pre-commit results
        if: steps.precommit.outcome == 'failure'
        run: |
          echo "Pre-commit checks failed. Please fix the issues and try again."
          exit 1
