name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
          - dev
          - staging
      confirm_destroy:
        description: 'Type "destroy" to confirm'
        required: true
        type: string
      double_confirm:
        description: 'Type environment name again'
        required: true
        type: string

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: azure-policy-${{ github.event.inputs.environment }}
  # Terraform variables
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VAR_location: ${{ secrets.AZURE_LOCATION || 'East US' }}
  TF_VAR_environment: ${{ github.event.inputs.environment }}
  TF_VAR_owner: platform-team
  TF_VAR_cost_center: development

jobs:
  validate-destroy:
    name: Validate Destroy Request
    runs-on: ubuntu-latest
    steps:
      - name: Validate Confirmations
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]; then
            echo "❌ First confirmation failed. You must type 'destroy'."
            exit 1
          fi

          if [ "${{ github.event.inputs.double_confirm }}" != "${{ github.event.inputs.environment }}" ]; then
            echo "❌ Second confirmation failed. You must type the environment name."
            exit 1
          fi

          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "❌ Production environment cannot be destroyed via workflow."
            exit 1
          fi

          echo "✅ All confirmations validated"

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    needs: validate-destroy
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/terraform

      - name: Terraform Plan Destroy
        id: plan
        run: |
          terraform plan -destroy -detailed-exitcode -out=destroy-plan
          echo "exitcode=$?" >> $GITHUB_OUTPUT
        working-directory: infrastructure/terraform

      - name: Upload Destroy Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-plan-${{ github.event.inputs.environment }}
          path: infrastructure/terraform/destroy-plan
          retention-days: 7

      - name: Terraform Destroy
        if: steps.plan.outputs.exitcode == 2
        run: terraform apply destroy-plan
        working-directory: infrastructure/terraform

      - name: Verify Destruction (via Terraform State)
        run: |
          echo "Verifying destruction..."
          # Check if terraform state is empty or contains no resources
          terraform show -no-color | head -20 || echo "No resources found in state"
          echo ""
          echo "✅ Destruction verification complete"
          echo "If you need to verify in Azure Portal, check that the resource group no longer exists."

      - name: Generate Destruction Summary
        if: success()
        run: |
          echo "## 🗑️ Infrastructure Destruction Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Environment Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Destroyed by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Cleanup Status" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ✅ Infrastructure destroyed" >> $GITHUB_STEP_SUMMARY
          echo "- **Resource Group:** Removed" >> $GITHUB_STEP_SUMMARY
          echo "- **Virtual Network:** Removed" >> $GITHUB_STEP_SUMMARY
          echo "- **Function Apps:** Removed" >> $GITHUB_STEP_SUMMARY
          echo "- **Storage Accounts:** Removed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Post-Destruction Tasks" >> $GITHUB_STEP_SUMMARY
          echo "1. Verify no orphaned resources in Azure Portal" >> $GITHUB_STEP_SUMMARY
          echo "2. Check for any remaining costs" >> $GITHUB_STEP_SUMMARY
          echo "3. Review backup retention policies" >> $GITHUB_STEP_SUMMARY

      - name: Create Destruction Issue
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const title = `🗑️ Infrastructure Destroyed - ${{ github.event.inputs.environment }}`;
            const body = `
            ## Infrastructure Destruction Completed

            **Environment:** ${{ github.event.inputs.environment }}
            **Destroyed by:** ${{ github.actor }}
            **Timestamp:** ${new Date().toISOString()}

            ### Destruction Summary
            All infrastructure resources for the ${{ github.event.inputs.environment }} environment have been successfully destroyed.

            ### Post-Destruction Checklist
            - [ ] Verify no orphaned resources in Azure Portal
            - [ ] Check Azure billing for any remaining costs
            - [ ] Review backup retention policies
            - [ ] Update documentation if needed
            - [ ] Close related infrastructure issues

            ### Resources Destroyed
            - Resource Group: rg-azurepolicy-${{ github.event.inputs.environment }}-eastus
            - Virtual Network and Subnets
            - Network Security Groups
            - App Service Plan
            - Function Apps
            - Storage Accounts
            - Application Insights (if enabled)
            - Key Vault (if enabled)

            **Workflow Run:** [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['infrastructure', 'destruction', 'cleanup', '${{ github.event.inputs.environment }}']
            });

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = `❌ Infrastructure Destruction Failed - ${{ github.event.inputs.environment }}`;
            const body = `
            ## Infrastructure Destruction Failed

            **Environment:** ${{ github.event.inputs.environment }}
            **Triggered by:** ${{ github.actor }}
            **Timestamp:** ${new Date().toISOString()}

            ### Failure Details
            The infrastructure destruction process failed. Please check the workflow logs for detailed error information.

            ### Manual Cleanup Required
            You may need to manually clean up resources in the Azure Portal:

            1. Navigate to Resource Group: rg-azurepolicy-${{ github.event.inputs.environment }}-eastus
            2. Review and delete remaining resources
            3. Delete the resource group
            4. Check for orphaned resources in other resource groups

            ### Troubleshooting Steps
            1. Check for resource locks
            2. Verify deletion permissions
            3. Look for dependencies preventing deletion
            4. Check for backup policies preventing deletion
            5. Review Azure service health

            **Workflow Run:** [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['infrastructure', 'destruction', 'failure', '${{ github.event.inputs.environment }}']
            });
